Repository annk15/MTGKeywordHelper, pull requests merged in 2024-08, with the labels that each got.

#44 Feature/design cards
  .gitignore
  interface/static/css/index.css
  interface/static/js/generate-card.js
  interface/static/js/scrollUp.js
  interface/static/js/search.js
  interface/templates/index.html
Labels: bug, enhancement, frontend

#51 Bug/searchbar autocomplete
  interface/static/css/index.css
  interface/templates/index.html
Labels: bug, frontend

#52 Back-To-Top button design
  interface/static/css/index.css
  interface/static/js/scrollUp.js
  interface/static/js/search.js
  interface/templates/index.html
Labels: enhancement, frontend

#55 Feature/new sync logic
  database/RuleManager.py
  database/blacklist.txt
  database/requirements.txt
  database/sync.py
  interface/static/js/generate-card.js
  server/server.py
Labels: enhancement, backend

#56 Port Frontend to React
  .env
  .gitignore
  README.md
  eslint.config.js
  index.html
  interface/clean.ps1
  interface/clean.sh
  interface/launch-site.ps1
  interface/launch-site.sh
  interface/requirements.txt
  interface/site.py
  interface/static/css/index.css
  interface/static/js/config.js
  interface/static/js/data-handler.js
  interface/static/js/data-notifier.js
  interface/static/js/generate-card.js
  interface/static/js/main.js
  interface/static/js/scrollUp.js
  interface/static/js/search.js
  interface/templates/index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/assets/Colors.css
  src/components/Card.jsx
  src/components/Card.module.css
  src/components/CardContainer.jsx
  src/components/CardContainer.module.css
  src/components/Header.jsx
  src/components/Header.module.css
  src/components/Searchbar.jsx
  src/components/Searchbar.module.css
  src/components/Searchbar.styles.jsx
  src/index.css
  src/main.jsx
  src/services/DataHandler.jsx
  src/utils/config.js
  vite.config.js
Labels: enhancement, backend, frontend
