Repository annk15/MTGKeywordHelper, pull requests merged in 2024-07, with the labels that each got.

#5 1 add landingpage
  frontend/index.html
  frontend/style.css
Labels: enhancement

#17 6 script for dynamic cards
  frontend/generateCard.js
  frontend/index.html
  frontend/search.js
  frontend/style.css
Labels: enhancement

#19 Add powershell scripts for running the backend on windows
  backend/database/docker-compose.yml
  backend/database/sync-database.ps1
  backend/database/sync-database.sh
  backend/database/sync.py
  backend/server/run-server.ps1
  backend/server/run-server.sh
Labels: enhancement

#24 Image endpoint
  backend/database/sync.py
  backend/server/server.py
Labels: enhancement

#27 Feature/cards from api
  frontend/generateCard.js
  frontend/style.css
Labels: enhancement, frontend

#28 Change folder structure and file-name
  .gitignore
  README.md
  backend/README.MD
  database/docker-compose.yml
  database/requirements.txt
  database/sync-database.ps1
  database/sync-database.sh
  database/sync.py
  interface/pages/index.html
  interface/scripts/generate-card.js
  interface/scripts/search.js
  interface/styles/index.css
  server/requirements.txt
  server/run-server.ps1
  server/run-server.sh
  server/server.py
Labels: enhancement

#29 Add keyword actions
  database/sync.py
Labels: enhancement, backend

#30 Frontend script for fetching card images and adding them to the card divs
  interface/pages/index.html
  interface/scripts/config.js
  interface/scripts/generate-card.js
  interface/styles/index.css
Labels: enhancement, frontend

#38 Add new endpoint for keywords
  server/server.py
Labels: enhancement, backend
